version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=mysql://user:password@db:3307/StudyBuddy
      - MYSQL_PASSWORD:/run/secrets/secret_db_pw
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_DATABASE: StudyBuddy  
      # MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/secret_db_pw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret_db_root_pw
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
       #mapping to port 3307 exterally (for some reason something on my computer uses 3306)
      - "3307:3306"
    secrets:
      - secret_db_pw
      - secret_db_root_pw
  
secrets:
  secret_db_pw:
    file: ./secrets/db_password.txt
  secret_db_root_pw:
    file: ./secrets/db_root_password.txt
    

